// meteor/tools/static-assets/skel-typescript/imports/ui/Info.tsx
import { useFind, useSubscribe } from "meteor/react-meteor-data";
import { LinksCollection, Link } from "../api/links";

export const Info = () => {
  const isLoading = useSubscribe("links");
  const links = useFind(() => LinksCollection.find());

  if (isLoading()) {
    return <div>Loading...</div>;
  }

  const makeLink = (link: Link) => {
    return (
      <li key={ link._id }>
        <a href={ link.url } target="_blank">{ link.title }</a>
      </li>
    );
  }

  return (
    <div>
      <h2>Learn Meteor!</h2>
      <ul>{ links.map(makeLink) }</ul>
    </div>
  );
};

// meteor/tools/static-assets/skel-vue/imports/ui/components/Info.vue
<script setup>
import { subscribe, autorun } from 'vue-meteor-tracker'
import { LinksCollection } from '/imports/api/links'

subscribe('links')
const links = autorun(() => LinksCollection.find({}).fetch()).result
</script>

<template>
  <h2 class="text-xl my-6 font-semibold">Learn Meteor!</h2>
  <ul class="list-disc underline">
    <li v-for="link of links" :key="link._id" class="hover:text-green-700">
      <a :href="link.url" target="_blank">{{ link.title }}</a>
    </li>
  </ul>
</template>
