// meteor/tools/static-assets/skel-chakra-ui/imports/ui/Hello.jsx
import React, { useState } from 'react';
import {Box, Button, Text} from "@chakra-ui/react";

export const Hello = () => {
  const [counter, setCounter] = useState(0);

  const increment = () => {
    setCounter(counter + 1);
  };

  return (
    <Box>
      <Button variant='outline' onClick={increment}>Click Me</Button>
      <Text fontSize={'xl'}>You've pressed the button {counter} times.</Text>
    </Box>
  );
};

// meteor/tools/static-assets/skel-solid/imports/ui/Hello.jsx
import { createSignal } from "solid-js";

export const Hello = () => {
  const [counter, setCounter] = createSignal(0);

  const increment = () => {
    setCounter(counter() + 1);
  };

  return (
    <div>
      <button onClick={increment}>Click Me</button>
      <p>You've pressed the button {counter()} times.</p>
    </div>
  );
}
