// thingsboard/ui-ngx/src/app/shared/components/dialog/alert-dialog.component.ts
///
/// Copyright © 2016-2026 The Thingsboard Authors
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///
///     http://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///

import { Component, Inject } from '@angular/core';
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { DialogComponent } from '@shared/components/dialog.component';
import { AppState } from '@core/core.state';
import { Router } from '@angular/router';
import { Store } from '@ngrx/store';

export interface AlertDialogData {
  title: string;
  message: string;
  ok: string;
  textMode?: boolean;
}

@Component({
    selector: 'tb-alert-dialog',
    templateUrl: './alert-dialog.component.html',
    styleUrls: ['./alert-dialog.component.scss'],
    standalone: false
})
export class AlertDialogComponent extends DialogComponent<AlertDialogComponent, boolean>{
  constructor(protected store: Store<AppState>,
              protected router: Router,
              public dialogRef: MatDialogRef<AlertDialogComponent, boolean>,
              @Inject(MAT_DIALOG_DATA) public data: AlertDialogData) {
    super(store,  router, dialogRef);
  }
}

<!--

    Copyright © 2016-2026 The Thingsboard Authors

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<h2 mat-dialog-title>{{data.title}}</h2>
<ng-container *ngIf="data.textMode; else htmlMode">
  <div mat-dialog-content [innerText]="data.message"></div>
</ng-container>
<ng-template #htmlMode>
  <div mat-dialog-content [innerHTML]="data.message | safe:'html'"></div>
</ng-template>
<div mat-dialog-actions class="flex items-center justify-end">
  <button mat-button color="primary" [mat-dialog-close]="true" cdkFocusInitial>{{data.ok}}</button>
</div>

// druid/web-console/src/dialogs/alert-dialog/alert-dialog.tsx
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { MaybeElement } from '@blueprintjs/core';
import { Button, Classes, Dialog, Icon, Intent } from '@blueprintjs/core';
import type { IconName } from '@blueprintjs/icons';
import classNames from 'classnames';
import React from 'react';

export interface AlertDialogProps {
  className?: string;
  icon?: IconName | MaybeElement;
  intent?: Intent;
  canEscapeKeyCancel?: boolean;
  canOutsideClickCancel?: boolean;
  autoFocusConfirm?: boolean;
  cancelButtonText?: string;
  onCancel?(): void;
  confirmButtonText?: string;
  onConfirm?(): void;
  onClose?(confirmed: boolean): void;
  children?: React.ReactNode;
  isOpen?: boolean;
}

export const AlertDialog = React.memo(function AlertDialog(props: AlertDialogProps) {
  const {
    className,
    icon,
    intent,
    canEscapeKeyCancel,
    canOutsideClickCancel,
    autoFocusConfirm,
    cancelButtonText,
    onCancel,
    confirmButtonText,
    onConfirm,
    onClose,
    children,
    isOpen,
  } = props;

  function handleCancel() {
    onCancel?.();
    onClose?.(false);
  }

  function handleConfirm() {
    onConfirm?.();
    onClose?.(true);
  }

  return (
    <Dialog
      className={classNames(Classes.ALERT, 'alert-dialog', className)}
      canEscapeKeyClose={canEscapeKeyCancel ?? true}
      canOutsideClickClose={canOutsideClickCancel ?? true}
      onClose={handleCancel}
      isOpen={isOpen ?? true}
    >
      <div className={Classes.ALERT_BODY}>
        <Icon icon={icon} size={40} intent={intent} />
        <div className={Classes.ALERT_CONTENTS}>{children}</div>
      </div>
      <div className={Classes.ALERT_FOOTER}>
        <Button
          intent={intent}
          text={confirmButtonText ?? 'OK'}
          onClick={handleConfirm}
          autoFocus={autoFocusConfirm ?? intent !== Intent.DANGER}
        />
        {cancelButtonText && <Button text={cancelButtonText} onClick={handleCancel} />}
      </div>
    </Dialog>
  );
});
